// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvRRQSpRf4ZTbZi51Sz_qRW9817AOXw7c',
    appId: '1:366974591989:web:9a9c4376ff7d4c0ced36bc',
    messagingSenderId: '366974591989',
    projectId: 'creationschools-dev',
    authDomain: 'creationschools-dev.firebaseapp.com',
    storageBucket: 'creationschools-dev.firebasestorage.app',
    measurementId: 'G-N33FWSBJY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF7GTTjwJkB0rdOf7Ypng9stC7-3RpTbM',
    appId: '1:366974591989:android:e492c92bf5db74f4ed36bc',
    messagingSenderId: '366974591989',
    projectId: 'creationschools-dev',
    storageBucket: 'creationschools-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGEwyRG9XNzvRC-IaX9ZA5iLYh7zjUcfk',
    appId: '1:366974591989:ios:bb57bf92b110a4c4ed36bc',
    messagingSenderId: '366974591989',
    projectId: 'creationschools-dev',
    storageBucket: 'creationschools-dev.firebasestorage.app',
    iosBundleId: 'com.creationschools.creationSchoolsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGEwyRG9XNzvRC-IaX9ZA5iLYh7zjUcfk',
    appId: '1:366974591989:ios:bb57bf92b110a4c4ed36bc',
    messagingSenderId: '366974591989',
    projectId: 'creationschools-dev',
    storageBucket: 'creationschools-dev.firebasestorage.app',
    iosBundleId: 'com.creationschools.creationSchoolsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvRRQSpRf4ZTbZi51Sz_qRW9817AOXw7c',
    appId: '1:366974591989:web:22e70e7d8ef874f1ed36bc',
    messagingSenderId: '366974591989',
    projectId: 'creationschools-dev',
    authDomain: 'creationschools-dev.firebaseapp.com',
    storageBucket: 'creationschools-dev.firebasestorage.app',
    measurementId: 'G-CX5PMDR99D',
  );
}
